package ru.pas_zhukov.unit.command;
// Generated by CodiumAI

import org.junit.Before;
import org.junit.jupiter.api.parallel.Execution;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import ru.pas_zhukov.config.AccountProperties;
import ru.pas_zhukov.controller.InputScanner;
import ru.pas_zhukov.controller.command.CloseAccountCommand;

import org.junit.Test;
import ru.pas_zhukov.service.AccountService;
import ru.pas_zhukov.service.UserService;

import java.io.ByteArrayInputStream;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.fail;
import static org.mockito.Mockito.*;

public class CloseAccountCommandTest {

    public ApplicationContext context;
    public AccountProperties properties;
    public InputScanner inputScanner;

    @Before
    public void init() {
        context = new AnnotationConfigApplicationContext("ru.pas_zhukov");
        properties = context.getBean(AccountProperties.class);
        inputScanner = context.getBean(InputScanner.class);
    }


    @Test
    public void testSuccessfulAccountClosure() {
        AccountService accountService = mock(AccountService.class);
        InputScanner inputScanner = mock(InputScanner.class);
        CloseAccountCommand closeAccountCommand = new CloseAccountCommand(accountService, inputScanner);

        when(inputScanner.parseInteger()).thenReturn(1);

        closeAccountCommand.execute();

        verify(accountService).deleteAccount(1);
        System.out.println("Account was closed.");
    }
}