name: Tests

on:
  push:
    branches: all
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: 12345
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Run Tests with Maven
      run: mvn -B install --file pom.xml
